import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service – Lab Buddy",
  description: "The terms governing your use of Lab Buddy.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16 text-text-main">
      <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm font-bold text-deep-mint hover:underline">
        ← Back to Lab Buddy
      </Link>

      <h1 className="mb-2 text-3xl font-black">Terms of Service</h1>
      <p className="mb-10 text-sm text-text-main/40">Last updated: March 2026</p>

      <div className="space-y-8 text-sm leading-relaxed text-text-main/70">

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">1. Acceptance of terms</h2>
          <p>
            By creating an account or using Lab Buddy, you agree to these Terms of Service
            and our Privacy Policy. If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">2. Description of service</h2>
          <p>
            Lab Buddy is a tool that uses artificial intelligence to provide plain-language
            explanations of medical laboratory results. It is intended for informational and
            educational purposes only.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">3. Not medical advice</h2>
          <p className="font-semibold text-text-main">
            Lab Buddy does not provide medical advice, diagnosis, or treatment recommendations.
          </p>
          <p className="mt-2">
            The explanations generated by Lab Buddy are not a substitute for professional
            medical advice. Always consult a qualified healthcare provider regarding any
            medical condition or before making health decisions. In an emergency, contact
            emergency services immediately.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">4. Eligibility</h2>
          <p>
            You must be at least 16 years old to create an account. By registering, you
            confirm that you meet this requirement. Users in jurisdictions with a higher
            age of digital consent must comply with local law.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">5. Your account</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>You are responsible for maintaining the confidentiality of your password.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
            <li>You must notify us immediately of any unauthorized access.</li>
            <li>You may not share your account with others or create multiple accounts to circumvent limits.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">6. Acceptable use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc space-y-1 pl-5">
            <li>Use the service for any unlawful purpose.</li>
            <li>Upload content that contains malware or attempts to harm the service.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
            <li>Misrepresent the AI-generated explanations as professional medical opinions.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">7. Intellectual property</h2>
          <p>
            Lab Buddy and its original content, features, and functionality are owned by
            Lab Buddy and protected by applicable intellectual property laws. You retain
            ownership of the lab report data you upload.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">8. Disclaimer of warranties</h2>
          <p>
            The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
            warranties of any kind, express or implied, including accuracy, completeness, or
            fitness for a particular purpose. AI-generated explanations may contain errors.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">9. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, Lab Buddy shall not be liable for any
            indirect, incidental, special, or consequential damages arising from your use of,
            or inability to use, the service — including any reliance on AI-generated content
            for medical decisions.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">10. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation of these terms.
            You may delete your account at any time from your account settings. Upon deletion,
            your data will be permanently removed within 30 days.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">11. Governing law</h2>
          <p>
            These terms are governed by applicable law. Disputes shall be resolved through
            good-faith negotiation first. If unresolved, they shall be subject to the
            jurisdiction agreed upon in writing between the parties.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">12. Changes to terms</h2>
          <p>
            We reserve the right to update these terms at any time. Material changes will be
            communicated with at least 14 days&apos; notice. Continued use of the service after
            the effective date constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-base font-black text-text-main">13. Contact</h2>
          <p>
            Questions about these terms:{" "}
            <a href="mailto:legal@labbuddy.app" className="text-deep-mint hover:underline">
              legal@labbuddy.app
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
